name: Java CI with Maven - car-mngt-api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0.23 # Usando uma versão mais estável
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: car_management_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install -U
      
    - name: Run tests
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/car_management_db?useSSL=false&serverTimezone=UTC                               
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      run: mvn test
